---
image: "buluma/github-action-molecule:4.0.5"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  retry: 1
  parallel:
    matrix:
      - image: "debian"
        tag: "jessie"
      - image: "debian"
        tag: "stretch"
      - image: "debian"
        tag: "wheezy"
      - image: "ubuntu"
        tag: "trusty"
      - image: "ubuntu"
        tag: "xenial"

molecule_staging:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "debian"
        tag: "jessie"
      - image: "debian"
        tag: "stretch"
      - image: "debian"
        tag: "wheezy"
      - image: "ubuntu"
        tag: "trusty"
      - image: "ubuntu"
        tag: "xenial"

role_testing:
  script:
    - image=${image} tag=${tag} ansible-galaxy install geerlingguy.apache-php-fpm
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "debian"
        tag: "jessie"
      - image: "debian"
        tag: "stretch"
      - image: "debian"
        tag: "wheezy"
      - image: "ubuntu"
        tag: "trusty"
      - image: "ubuntu"
        tag: "xenial"

galaxy:
  script:
    - pwd && ls -ltra tests && ansible-galaxy role install -vr requirements.yml --ignore-errors && ansible-playbook tests/test.yml -vvv
    # - pwd && cd test && ls -ltra && ansible-playbook test.yml -vvv
