---
roles:
  - name: buluma.bootstrap
  - name: geerlingguy.apache
  - name: geerlingguy.repo-remi
  - name: geerlingguy.php-versions
  - name: geerlingguy.php
collections:
  - name: community.general
