---
roles:
  - name: buluma.bootstrap
  - name: geerlingguy.apache
  - name: geerlingguy.repo-remi
  - name: geerlingguy.php-versions
  - name: geerlingguy.php
  - name: geerlingguy.apache-php-fpm
collections:
  - name: community.general
