---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: geerlingguy.repo_remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.apache
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.apache-php-fpm
