---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: geerlingguy.repo-remi
    - role: geerlingguy.apache
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
