---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Enable mod_proxy_fcgi.
      ansible.builtin.file:
        src: "{{ apache_server_root }}/mods-available/{{ item }}"
        dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
        state: link
      with_items:
        - proxy.load
        - proxy_fcgi.load
      notify: restart apache
      when: ansible_os_family == 'Debian'
